import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";


import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Threads",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <ClerkProvider >
            <html lang='en'>
                <body className={`${inter.className} bg-dark-1`}>
                    <div className="flex min-h-screen items-center justify-center">
                        {children}
                    </div>
                </body>
            </html>
        </ClerkProvider>
    );
}